# 应用名称
server:
  port: 9090

spring:
  application:
    name: demo

logging:
  config: classpath:logback-spring.xml

#测试环境
#elmUrl: http://10.219.87.224:8080/veivo-boot/spc/spiConfig/listData
#正式环境
elmUrl: http://elm.desaysv.com/veivo-boot/spc/spiConfig/listData


